# Generated by Django 3.2.6 on 2021-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210823_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
